"""Authentication and Session Management API Router.

This router manages user identity lifecycles for the credit bureau platform,
including user registration with automatic TOTP secret provisioning for privileged roles,
credential verification with brute-force lockout protection, two-step Multi-Factor
Authentication (MFA) challenge resolution, cryptographically rotated single-use refresh tokens,
token revocation on logout, and current user profile inspection.

Architecture Tier:
    API / Presentation Layer (`backend/app/routers/`).

Key Dependencies & Callers:
    - Depends on `app.auth` cryptographic helpers and `app.database.get_db`.
    - Called directly by the Next.js frontend (`/login` page, `CarbonShell.tsx` session management)
      and programmatic API clients.

Regulatory & Compliance Context:
    - Privacy Act 1988 (Cth) Part IIIA & Australian Privacy Principle 11:
      Mandates strict access control and authentication protocols for all actors accessing
      or modifying credit reporting data.
"""

from fastapi import APIRouter, Depends, HTTPException, status, Header
from sqlalchemy.orm import Session
from pydantic import BaseModel, EmailStr
from typing import Optional, Dict, Any

from app.database import get_db
from app.models import User, RoleEnum
from app.auth import (
    hash_password, verify_password,
    create_access_token, create_refresh_token, decode_token,
    generate_totp_secret, verify_totp,
    get_current_user,
    record_failed_login, is_account_locked, reset_failed_logins,
    is_refresh_token_used, mark_refresh_token_used, is_token_revoked, revoke_token
)

router = APIRouter(prefix="/api/auth", tags=["auth"])


class RegisterRequest(BaseModel):
    """Payload schema for user account registration.

    Attributes:
        email: Unique user email address.
        password: Raw password (minimum complexity verified downstream).
        role: RBAC RoleEnum (ADMIN, PROVIDER, ANALYST, or SUBJECT).
        tenant_id: Organization code for providers (e.g. 'PRV-CBA-001').
        entity_id: Subject file UUID for consumer self-service accounts.
    """
    email: str
    password: str
    role: RoleEnum = RoleEnum.SUBJECT
    tenant_id: Optional[str] = None
    entity_id: Optional[str] = None


class LoginRequest(BaseModel):
    """Payload schema for initial credential submission.

    Attributes:
        email: User email address.
        password: Raw password string.
    """
    email: str
    password: str


class MFAVerifyRequest(BaseModel):
    """Payload schema for completing the TOTP MFA challenge.

    Attributes:
        temp_token: Intermediate JWT issued during initial login with `mfa_pending=True`.
        mfa_token: Alias for temp_token for API flexibility.
        code: 6-digit numeric TOTP code generated by an authenticator application.
        totp_code: Alias for code.
    """
    temp_token: Optional[str] = None
    mfa_token: Optional[str] = None
    code: Optional[str] = None
    totp_code: Optional[str] = None


class RefreshRequest(BaseModel):
    """Payload schema for rotating a refresh token.

    Attributes:
        refresh_token: Valid signed HS256 refresh token string.
    """
    refresh_token: str


class LogoutRequest(BaseModel):
    """Payload schema for explicit session termination.

    Attributes:
        refresh_token: Optional refresh token to blacklist alongside the Bearer token.
    """
    refresh_token: Optional[str] = None


@router.post("/register")
def register(req: RegisterRequest, db: Session = Depends(get_db)):
    """Registers a new user account and provisions MFA credentials if required.

    Privileged operational roles (ADMIN, ANALYST, PROVIDER) automatically have
    MFA enabled and receive an RFC 6238 TOTP secret key for authenticator app enrollment.

    Args:
        req: RegisterRequest payload containing credentials and desired role.
        db: Scoped database session.

    Returns:
        JSON response with user details and initial base32 TOTP secret if applicable.

    Raises:
        HTTPException(400): If the email is already registered.
    """
    existing = db.query(User).filter(User.email == req.email).first()
    if existing:
        raise HTTPException(status_code=400, detail="Email already registered")
    
    # REVIEW-SECURITY: Privileged roles (ADMIN, ANALYST, PROVIDER) strictly mandate MFA
    totp_secret = generate_totp_secret() if req.role in [RoleEnum.ADMIN, RoleEnum.ANALYST, RoleEnum.PROVIDER] else None
    
    user = User(
        email=req.email,
        password_hash=hash_password(req.password),
        role=req.role,
        tenant_id=req.tenant_id,
        entity_id=req.entity_id,
        totp_secret=totp_secret,
        mfa_enabled=True if totp_secret else False
    )
    db.add(user)
    db.commit()
    db.refresh(user)
    
    return {
        "status": "success",
        "user_id": user.id,
        "email": user.email,
        "role": user.role,
        "mfa_required": user.mfa_enabled,
        "totp_secret": totp_secret # Expose only upon registration so user can scan authenticator
    }


@router.post("/login")
def login(req: LoginRequest, db: Session = Depends(get_db)):
    """Authenticates username/password credentials and initiates the session or MFA challenge.

    Enforces brute-force lockout (5 failed attempts triggers 15-minute lockout). If the
    user's role mandates MFA, issues an intermediate temporary token (`mfa_pending=True`)
    requiring completion via `/api/auth/mfa/verify`. Otherwise, issues full access and refresh tokens.

    Args:
        req: LoginRequest credentials.
        db: Scoped database session.

    Returns:
        JSON payload indicating whether MFA is required, containing tokens and user profile.

    Raises:
        HTTPException(429): If account is locked due to excessive failed attempts.
        HTTPException(401): If credentials are invalid.
    """
    # 1. Check brute-force lockout status
    # REVIEW-SECURITY: Enforce 15-minute account lockout after 5 consecutive failed attempts
    if is_account_locked(req.email):
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Account is temporarily locked due to multiple failed login attempts. Please try again later."
        )
        
    user = db.query(User).filter(User.email == req.email).first()
    if not user or not verify_password(req.password, user.password_hash):
        count, is_locked = record_failed_login(req.email)
        if is_locked:
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail="Account is temporarily locked due to multiple failed login attempts. Please try again later."
            )
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid email or password")
    
    # 2. Reset lockout on successful credentials
    reset_failed_logins(req.email)
    
    # 3. Check if role requires TOTP MFA (Admin, Analyst, Provider)
    if user.role in [RoleEnum.ADMIN, RoleEnum.ANALYST, RoleEnum.PROVIDER] and user.mfa_enabled and user.totp_secret:
        # REVIEW-SECURITY: Issue a temporary token valid strictly for MFA verification with mfa_pending=True
        temp_token = create_access_token(
            {"sub": user.id, "email": user.email, "role": user.role, "mfa_pending": True},
            expires_delta=None
        )
        return {
            "mfa_required": True,
            "temp_token": temp_token,
            "mfa_token": temp_token,
            "user": {
                "id": user.id,
                "email": user.email,
                "role": user.role,
                "tenant_id": user.tenant_id,
                "entity_id": user.entity_id
            },
            "message": "TOTP MFA code required."
        }
    
    # 4. Otherwise, issue full operational tokens
    access_token = create_access_token({
        "sub": user.id,
        "email": user.email,
        "role": user.role,
        "tenant_id": user.tenant_id,
        "entity_id": user.entity_id
    })
    refresh_token = create_refresh_token({"sub": user.id})
    
    return {
        "mfa_required": False,
        "access_token": access_token,
        "refresh_token": refresh_token,
        "user": {
            "id": user.id,
            "email": user.email,
            "role": user.role,
            "tenant_id": user.tenant_id,
            "entity_id": user.entity_id
        }
    }


@router.post("/mfa/verify")
def verify_mfa(req: MFAVerifyRequest, db: Session = Depends(get_db)):
    """Verifies a 6-digit TOTP code against the intermediate MFA token.

    Validates that the token carries the `mfa_pending` claim, verifies the TOTP code
    against the user's stored secret, and upon success issues the full operational
    access token and refresh token.

    Args:
        req: MFAVerifyRequest containing the intermediate token and 6-digit code.
        db: Scoped database session.

    Returns:
        JSON response with finalized access_token, refresh_token, and user metadata.

    Raises:
        HTTPException(400): If tokens or codes are missing, or token lacks mfa_pending.
        HTTPException(401): If TOTP code is incorrect or expired.
        HTTPException(404): If user does not exist.
    """
    token = req.mfa_token or req.temp_token
    code = req.totp_code or req.code
    if not token or not code:
        raise HTTPException(status_code=400, detail="MFA token and verification code are required")
        
    payload = decode_token(token)
    # REVIEW-SECURITY: Ensure the caller cannot submit an already-authenticated access token to this endpoint
    if not payload.get("mfa_pending"):
        raise HTTPException(status_code=400, detail="Invalid MFA token: Missing mfa_pending claim")
    
    user_id = payload.get("sub")
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    if not verify_totp(user.totp_secret, code):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid TOTP authentication code")
        
    access_token = create_access_token({
        "sub": user.id,
        "email": user.email,
        "role": user.role,
        "tenant_id": user.tenant_id,
        "entity_id": user.entity_id
    })
    refresh_token = create_refresh_token({"sub": user.id})
    
    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "user": {
            "id": user.id,
            "email": user.email,
            "role": user.role,
            "tenant_id": user.tenant_id,
            "entity_id": user.entity_id
        }
    }


@router.post("/refresh")
def refresh(req: RefreshRequest, db: Session = Depends(get_db)):
    """Rotates a single-use refresh token and issues a new access/refresh pair.

    Implements Refresh Token Rotation (RTR) under RFC 6749 Section 10.4.
    If an already-used refresh token is presented, treats it as a token theft
    attempt and rejects the request with HTTP 401.

    Args:
        req: RefreshRequest holding the current refresh token.
        db: Scoped database session.

    Returns:
        JSON response with new access_token and new refresh_token.

    Raises:
        HTTPException(400): If token is not of type 'refresh'.
        HTTPException(401): If token has already been rotated or revoked.
        HTTPException(404): If user is not found.
    """
    payload = decode_token(req.refresh_token)
    if payload.get("token_type") != "refresh":
        raise HTTPException(status_code=400, detail="Token is not a refresh token")
        
    jti = payload.get("jti")
    # REVIEW-SECURITY: Detect refresh token reuse attacks (theft / replay)
    if is_refresh_token_used(jti):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh token reuse detected: Token has already been rotated"
        )
    if is_token_revoked(jti):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh token has been revoked"
        )
        
    user_id = payload.get("sub")
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    # Rotate: invalidate old refresh token immediately
    mark_refresh_token_used(jti)
    
    new_access_token = create_access_token({
        "sub": user.id,
        "email": user.email,
        "role": user.role,
        "tenant_id": user.tenant_id,
        "entity_id": user.entity_id
    })
    new_refresh_token = create_refresh_token({"sub": user.id})
    
    return {
        "access_token": new_access_token,
        "refresh_token": new_refresh_token
    }


@router.post("/logout")
def logout(
    req: Optional[LogoutRequest] = None,
    authorization: Optional[str] = Header(None),
    db: Session = Depends(get_db)
):
    """Invalidates the caller's active Bearer access token and refresh token.

    Adds token JTIs and raw signatures to the blacklist to guarantee immediate
    session revocation without waiting for token expiration.

    Args:
        req: Optional LogoutRequest payload containing a refresh token.
        authorization: Optional HTTP Authorization Bearer header.
        db: Scoped database session.

    Returns:
        JSON success confirmation.
    """
    # Invalidate current access token
    if authorization and authorization.startswith("Bearer "):
        access_token = authorization.split(" ")[1].strip()
        try:
            payload = decode_token(access_token)
            jti = payload.get("jti")
            if jti:
                revoke_token(jti)
            revoke_token(access_token)
        except Exception:
            revoke_token(access_token)

    # Invalidate provided refresh token
    if req and req.refresh_token:
        try:
            payload = decode_token(req.refresh_token)
            jti = payload.get("jti")
            if jti:
                revoke_token(jti)
            revoke_token(req.refresh_token)
        except Exception:
            revoke_token(req.refresh_token)

    return {"status": "success", "message": "Successfully logged out. Tokens invalidated."}


@router.get("/me")
def me(current_user: User = Depends(get_current_user)):
    """Returns profile and identity information for the current authenticated user.

    Requires a valid, fully-authenticated access token.

    Args:
        current_user: User model injected via FastAPI `Depends(get_current_user)`.

    Returns:
        JSON dictionary with id, email, role, tenant_id, and entity_id.
    """
    return {
        "id": current_user.id,
        "email": current_user.email,
        "role": current_user.role,
        "tenant_id": current_user.tenant_id,
        "entity_id": current_user.entity_id
    }
